# Generated by Django 4.2.20 on 2025-09-18 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPhrase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phrase', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_securityphrases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
